packages:
  - ./*
allowBuilds:
  '@parcel/watcher': true
  electron: true
catalog:
  electron: ^42.2.0
  npm-run-all2: ^8.0.4
  sass: ^1.99.0
  vite: ^8.0.8
onlyBuiltDependencies:
  - '@parcel/watcher'
  - electron
